
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className='!bg-darkGreen-800 !font-workSans '
      >
        {children}
      </body>
    </html>
  );
}
